### ISSUE TITLE
Default Interface methods require an implementation

### ISSUE THREAD

**Issue by fmorris2** [janino-compiler/janino#126]
Example Java Code:
```
public interface BaseTestable {
   public void test();
}

public interface Testable extends BaseTestable {
   @Override
   default public void test() {
      System.out.println("test");
   }
}

public class Test implements Testable {
   //blank implementation
}
```

If you try to compile this to Groovy, the Janino compiler states `test` is an abstract method which needs to be implemented in `Test`.

Is this a Groovy limitation, a bug, or something else?

**Comment by aunkrig** [comment]
Hey Fred,

sorry for the late response, but here is an answer:

To date, JANINO still produces Java 6 .class files, which is fine because all newer JVMs can still load Java 6 .class files, and JANINO doesn't require the Java 7+ .class file features.

However Java 8 introduced "default methods", and JANINO can not compile these (as you observed), nor can it *invoke* them. Java 8+ has lots of them in the JRE libraries, and many parts of the JRE libraries thus cannot be user by JANINO scripts. And that is actually an even *bigger* problem!

So why does JANINO still generate only Java 6 .class files? Because Java 7+ dictates that each method must have a ```StackMapTable``` attribute, and that attribute is *very* complicated to generate. My opinion is that the introduction of the ```StackMapTable``` attribute was a major design mistake of SUN, because it is totally redundant (it only makes it easier/faster for JVMs to load a class), and is such a burden for applications that generate .class files, like JANINO. Also, JVMs must still be able to do without it, because Java 6- .class files don't have it. The requirement of having that attribute takes away so much of the beautiful simplicity of the class file format... what a drag.

But, because it is now inevitable, I have added support for generation of the ```StackMapTable``` attribute, but it is still experimental because, in rare cases, the generated attribute is still buggy, and you get ```VerifyError```s when you load the JANINO-generated .class file.

However it is possible to enable the generation of the ```StackMapTable``` attribute, and then JANINO can both *compile* default methods (as in your example) and *invoke* default methods. I have added a test case ```org.codehaus.commons.compiler.tests.ReportedBugsTest.testIssue126()``` that demonstrates how you set the "source version" and "target version" of the ```ISimpleCompiler``` to 8, and then compiles and loads your code example.

That JANINO feature is not yet released, but the TRUNK version has it.

Could you please test if that works "well enough" for your purposes?

**Comment by aunkrig** [comment]
Ping.
