### ISSUE TITLE
Static Fields of Inner Classes

### ISSUE THREAD

**Issue by cvogt729** [janino-compiler/janino#179]
I found another deviation between JAVAC and Janino. I am using Janino from the latest commit to the master branch: ccf56a932843c1484278378f1a6aefc2fb37130f. I am using `SimpleCompiler` to compile the following code:
```java
public class Test4 {
  public static void main(String[] args){
    new Test4().new Inner();
  }
  class Inner {
    private static int x = 0;
    public Inner(){
      System.out.println("Hello World!");
    }
  }
}
```
When invoking `SimpleCompiler` in Windows PowerShell with OpenJDK 11.0.14.1:
```powershell
java '-cp' 'janino.jar;commons-compiler.jar' 'org.codehaus.janino.SimpleCompiler' 'Test4.java' 'Test4'
```
There is no error, and it prints `Hello World!` to the console. However, this should result in a compilation error according to JAVAC:
```
Test4.java:6: error: Illegal static declaration in inner class Test4.Inner
    private static int x = 0;
                       ^
  modifier 'static' is only allowed in constant variable declarations
```
https://stackoverflow.com/questions/1953530/why-does-java-prohibit-static-fields-in-inner-classes

**Comment by aunkrig** [comment]
Yes, Oracle (at that time SUN) put a lot of unnecessary restrictions on interfaces, nested types and anonymous classes. I asked the experts several times why all those restrictions exist, and never got convincing answers. AFAIK the only restrictions that are really necessary are:
- Every classes extends (at most) one class
- Interfaces don't have non-static fields
- No loops in the inheritance graph

As of Java 17, most of the unnecessary restrictions were eventually removed... hooray!

The one restriction which you mention here is a good example for one that is **only** imposed by the JLS, not the JRE. What a massive design error back then...

Rather than regarding this as a bug, I consider calling it "a later language feature that Janino implements even for earlier JREs" (similar to the "enhanced try-with-resources statement").

What do you think about that?

**Comment by cvogt729** [comment]
That sounds reasonable to me.
