### ISSUE TITLE
Bad case in Basic example

### ISSUE THREAD

**Issue by Joey777210** [janino-compiler/janino#199]
Hi, I'm new to janino, and try to get some example on homepage. But there is a ambiguous reference of the first example:
![image](https://user-images.githubusercontent.com/53630996/233359359-9624734f-c6dc-4533-9dc0-b40debf77871.png)

Run that code on JDK1.8, it gives `ambiguous reference`.
This can be a bad guide for beginners, maybe replace with another case?

**Comment by Joey777210** [comment]
See this two functions:
![image](https://user-images.githubusercontent.com/53630996/233360849-c8b8a962-4218-4a72-b845-78224a8c45f7.png)

**Comment by Joey777210** [comment]
And also, how can I use evaluate on pure `int` type expression?

**Comment by aunkrig** [comment]
That example code doesn't work since Janino 3.0.16, when I changed the signature of

    org.codehaus.commons.compiler.IExpressionEvaluator.evaluate(int idx, @Nullable Object[] arguments)

to

    org.codehaus.commons.compiler.IExpressionEvaluator.evaluate(int idx, @Nullable Object... arguments)

, assuming that this is a compatible API change. (As you proved, it is not.)

Because it is not easily possible to revert that API change without breaking application code, I fixed the code example instead.

Thank you for reporting the problem! Please re-test.

**Comment by Joey777210** [comment]
That looks fine, Thanks.
