### ISSUE TITLE
Does not compile my project

### ISSUE THREAD

**Issue by cgille** [janino-compiler/janino#35]
Dear Janino developers,

I am developing a free java program for life scientists and would be very interested in a fast java compiler like janino.

Some Java classes are quite big and take several seconds to compile with Oracle javac. 
This makes  code-editing / recompilation cumbersome. Therefore  janino would help a lot.
For final compilation I would probably still trust Oracle Javac but for rapid error fixing and developing 
I would prefer janino.

Unfortunately, janino does not compile many of my Java-files. I would need to change too many lines of code
for example explicit casting the results of Map#get and Collection#get.

Is there a chance to get these issues resolved in janino?
I guess, that there are only very few syntactical constructs which are not yet supported in janino.

Many thanks for developing this nice software

Cheers 
Christoph

**Comment by aunkrig** [comment]
Hi there,

what you are trying to do is quite unusual. People typically use JANINO to compile Java expressions or small snippets of code - not entire applications and class hierarchies.

JANINO scans and parses the full Java 8 syntax, but does not _understand_ some constructs, namely "generic types", which is why one has to type-cast the result of, e.g., ```Map.get()```. Generic types are terribly complicated, which is why they are not implemented to date, and are not required for the many "simple" applications.

However JANINO attempts to continue compiling after an error (if it is not a parse error), mainly to give the programmer a chance to fix _more than one_ bug before re-compiling, but eventually does not save the generated class files, and terminates with non-zero status.

It could be possible to implement a command line switch that modifies this behavior such that the class files are _always_ stored, even if they may contain invalid code, which will (probably) cause ```VerifyError```s when the classes are loaded.

Would that partial solution be helpful for your application?


CU

Arno

**Comment by cgille** [comment]
Dear Arno,





many thanks for the quick answer.



Generic types are heavily used in my code.

Even if the compilation would terminate with return code zero, the missing castings would produce extremely long compiler message lists.

I think that this would not be helpful.





I guess, that implementing  "generic types" in the compiler is quite difficult to do. Will it be implemented in Janino in the future?



Perhaps a workaround easier to implement could be to add a command line option which instructs Janino to

cast return values of type java.lang.Object in whatever is required in the respective context.



I will notice those errors when I use  javac or ecj from time to time. Even javac overlooks syntax errors which are only detected by ecj, so I am used in trying different compilers.



I am using Emacs for several reasons.  Can Janino produce Emacs style compilation messages?



Cheers



Christoph









________________________________
Von: Arno Unkrig [notifications@github.com]
Gesendet: Montag, 18. Dezember 2017 12:22
An: janino-compiler/janino
Cc: Gille, Christoph; Author
Betreff: Re: [janino-compiler/janino] Does not compile my project (#35)


Hi there,

what you are trying to do is quite unusual. People typically use JANINO to compile Java expressions or small snippets of code - not entire applications and class hierarchies.

JANINO scans and parses the full Java 8 syntax, but does not understand some constructs, namely "generic types", which is why one has to type-cast the result of, e.g., Map.get(). Generic types are terribly complicated, which is why they are not implemented to date, and are not required for the many "simple" applications.

However JANINO attempts to continue compiling after an error (if it is not a parse error), mainly to give the programmer a chance to fix more than one bug before re-compiling, but eventually does not save the generated class files, and terminates with non-zero status.

It could be possible to implement a command line switch that modifies this behavior such that the class files are always stored, even if they may contain invalid code, which will (probably) cause VerifyErrors when the classes are loaded.

Would that partial solution be helpful for your application?

CU

Arno

**Comment by aunkrig** [comment]
> Am 18.12.2017 um 15:08 schrieb cgille <notifications@github.com>:
> 
> Dear Arno,
> 
> 
> 
> 
> 
> many thanks for the quick answer.
> 
> 
> 
> Generic types are heavily used in my code.
> 
> Even if the compilation would terminate with return code zero, the missing castings would produce extremely long compiler message lists.
> 
> I think that this would not be helpful.
> 
> 
> 
> 
> 
> I guess, that implementing "generic types" in the compiler is quite difficult to do. Will it be implemented in Janino in the future?

Honestly... I don‘t think so. I don‘t have the time to implement all the features of Java 5, 6, 7, 8, 9, ... so JANINO remains focused on what it is: a super-small, super-fast compiler for embedded applications. Plus some advanced language features that someone requests and are easy to implement.

> Perhaps a workaround easier to implement could be to add a command line option which instructs Janino to cast return values of type java.lang.Object in whatever is required in the respective context.

Actually that is what JANINO already does - in the „advanced FOR statement“. Unfortunately, in other contexts it is extremely difficult to tell „what is required“, and that‘s why JANINO doesn‘t do it. Sorry!

> I will notice those errors when I use javac or ecj from time to time. Even javac overlooks syntax errors which are only detected by ecj, so I am used in trying different compilers.
> 
> I am using Emacs for several reasons. Can Janino produce Emacs style compilation messages?

Honestly I don‘t know what emacs-style compilation messages look like, but it would be easy to implement that. Could you please create a separate GITHUB issue and provide (or link to) a good specification?


CU Arno

**Comment by oontvoo** [comment]
Hi cgille, please allow to contribute my two-cents on this matter.

As someone who actually uses Janino in an enterprise-level software, I can say the value of Janino comes into place when there is a need to quickly compile and run (a large amount of) generated code in real-time.  We have code that could take ~30 mins to compile/load if done with javac, whereas janino would only take less than a minute. This is where we see a difference.

As you said, your projects took "several seconds" to compile with Oracle's javac. That is not a "big" number. In fact, if you have proper build/make system in place, it probably will not even take as much since the build/make system will be able to detect changes and only re-compile the part that was changed and not the whole system. So perhaps, the better solution for your case might be in that area.

Obviously, I'm not trying to discourage people from using Janino, as I really believe it is a great piece of software, but it's rather important to solve the right problem with the right tools.

Best,

Vy

**Comment by cgille** [comment]
Dear Vy,


many thanks to point this out.

Cool -  30 min vs. 1min - that is a big difference!


When  fixing errors and frequently compiling and testing the application,
it matters whether compilation of  the  class under consideration takes 9 or only 2 seconds.

It sounds amayzing to me that Janino is that much faster which indicates that the quality of code of Janino is very high and that your programming techniques are superior.

I will whatch the Janino project and reconsider Janino, once the  generic types are introduced.


I wish you all the best and success with your Janino project

best regards

Christoph

________________________________

Von: Vy Nguyen [notifications@github.com]
Gesendet: Dienstag, 19. Dezember 2017 07:11
An: janino-compiler/janino
Cc: Gille, Christoph; Author
Betreff: Re: [janino-compiler/janino] Does not compile my project (#35)


Hi cgille, please allow to contribute my two-cents on this matter.

As someone who actually uses Janino in an enterprise-level software, I can say the value of Janino comes into place when there is a need to quickly compile and run (a large amount of) generated code in real-time. We have code that could take ~30 mins to compile/load if done with javac, whereas janino would only take less than a minute. This is where we see a difference.

As you said, your projects took "several seconds" to compile with Oracle's javac. That is not a "big" number. In fact, if you have proper build/make system in place, it probably will not even take as much since the build/make system will be able to detect changes and only re-compile the part that was changed and not the whole system. So perhaps, the better solution for your case might be in that area.

Obviously, I'm not trying to discourage people from using Janino, as I really believe it is a great piece of software, but it's rather important to solve the right problem with the right tools.

Best,

Vy
