### ISSUE TITLE
Caused by: java.lang.NoSuchMethodError: org.codehaus.commons.compiler.Location.getLineNumber()S

### ISSUE THREAD

**Issue by skydive241** [janino-compiler/janino#43]
Since v3.0.2., using of getLineNumber() ends up in compilation error:
Caused by: java.lang.NoSuchMethodError: org.codehaus.commons.compiler.Location.getLineNumber()S

I think, maybe the error occurs in Location.java:
...
```
    public static final Location NOWHERE = new Location("<internally generated location>", **(short)** -1, **(short)** -1);

    @Nullable private final String optionalFileName;
    private final int              lineNumber;
    private final int              columnNumber;
...
    public
    Location(@Nullable String optionalFileName, **int** lineNumber, **int** columnNumber) {
        this.optionalFileName = optionalFileName;
        this.lineNumber       = lineNumber;
        this.columnNumber     = columnNumber;
    }

```

Greetings,
Patrick

**Comment by aunkrig** [comment]
Hey there,

your description provides very little context of what you're doing... so here's my best guess:

Your code is calling ```Location.getLineNumber()```, and you _compiled_ your code against JANINO version 3.0.1 or earlier, and you _run_ your code against JANINO version 3.0.2 or later.

The reason being is that the return type of method ```Location.getLineNumber()``` was changed from ```short``` to ```int``` in version 3.0.2, which is reasonable because compilation units can readily have more than 32K (or 64K) lines of code.

Until version 3.0.1, the return type was ```short``` because the class file format allows only line numbers up to 64K in its ```LineNumberTable```, but that was a bad design decision because the ```Location``` class is used for many other purposes as well.

Please make sure that you compile _and_ run against the same JANINO version.

**Comment by skydive241** [comment]
Hi and thank you for your answer.

Shame on me, and of course you're right - I simply forgot to change the libraries used for my eclipse-project.... and didn't think any further....

I "adopted" scriptella, an etl-tool using janino, and began making it fitting to my needs - janino is great for etl-tasks, many thanks for doing a great job! :)

And, if you're interested, another great tool for your list of projects using janino:
http://scriptella.org/

Greetings from Mainz,
Patrick

**Comment by ejboy** [comment]
I apologize for the noise, but I came across this issue when working on https://github.com/scriptella/scriptella-etl/issues/30.  @skydive241 just wanted to let you know that 1.2 release is now available with support for 3.x
Also would like to thank Arno for the awesome product!

**Comment by aunkrig** [comment]
Thank you 🤗.
