### ISSUE TITLE
Parse Type inference syntax

### ISSUE THREAD

**Issue by aunkrig** [janino-compiler/janino#78]
In order to make static code analysis and code manipulation possible, parse the "type inference" syntax:
* Type inference for generic instance creation (a Java 7 feature)
* Local variable type inference (a Java 10 feature)
* Lambda parameter type inference (a Java 11 feature)

*Compilation* is not (yet) possible.

**Comment by aunkrig** [comment]
Implemented.
@gchallen: Please test

**Comment by aunkrig** [comment]
Yep.

**Comment by richard-steiger** [comment]
Arno,

I had intended to pull and test your changes, and still intend to, but 
have been hit with an urgent assignment that's had to take precedence.  
I'm hoping to test sometime this coming week.

-rjs

**Comment by richard-steiger** [comment]
Arno,

Contrary to my intentions, our project, on which I'd planned to use 
janino, has taken a different tack, and we're looking to integrate with 
at least one of the other open source static code analysis projects, PMD 
and/or sonar-java.  Since they already contain full java parsers for 
Java8 and above, this renders our efforts to leverage janino moot.

I remain very grateful for your prompt response when I brought the 
method reference issue to you.  Unfortunately, I don't have the charter 
nor bandwidth to verify the fixes, at least at this time.  I'll likely 
get back to at least testing janino on a future side-project, but that's 
not much comfort to you.

Best regards,

-rjs

**Comment by aunkrig** [comment]
Hey Richard,

no problem at all. Please notice that the JANINO parser now implements the complete Java 11 syntax (see above).

**Comment by richard-steiger** [comment]
Thanks for letting me know.

Cheers,

-rjs

**Comment by richard-steiger** [comment]
Hi Arno,
 
I retested Janino in the same project we've discussed.  The following is a report of errors raised by the Parser (each error occupies 2 lines): 
 
parsing "/Users/usteiri/Pearson/GLP/code/glp-roster-management/src/main/java/com/pearson/glp/roster/data/model/LearningAsset.java": File 'LearningAsset.java', Line 86, Column 15: IDENTIFIER expected instead of '@'
   private Map<@NotBlank String, @NotBlank String> extensions;
 parsing "/Users/usteiri/Pearson/GLP/code/glp-roster-management/src/main/java/com/pearson/glp/roster/data/model/Extends.java": File 'Extends.java', Line 42, Column 16: IDENTIFIER expected instead of '@'
   private List<@NotNull AssetRelationship> sources = new ArrayList<>();
 parsing "/Users/usteiri/Pearson/GLP/code/glp-learning-product-builder/src/main/java/com/pearson/glp/lpb/utils/CommonUtils.java": File 'CommonUtils.java', Line 84, Column 17: Default interface methods not implemented
   default <T> T convertJsonToObject(String jsonFile, Class<T> classType) throws ServiceException {
 parsing "/Users/usteiri/Pearson/GLP/code/glp-learning-experience-composition-kernel/src/main/java/com/pearson/glp/composer/service/impl/LearningExperienceServiceImpl.java": File 'LearningExperienceServiceImpl.java', Line 548, Column 35: ')' expected instead of '::'
         .map(this.productConverter::convert)
 parsing "/Users/usteiri/Pearson/GLP/code/glp-assignment-management/src/main/java/com/pearson/glp/assignment/model/LearningExperience.java": File 'LearningExperience.java', Line 76, Column 16: IDENTIFIER expected instead of '@'
   private List<@NotNull AssetGraphItem> assetGraph;
 parsing "/Users/usteiri/Pearson/GLP/code/glp-productization-service/src/main/java/com/pearson/glp/pdz/utils/CommonUtils.java": File 'CommonUtils.java', Line 58, Column 17: Default interface methods not implemented
   default <T> T convertJsonToObject(String jsonFile, Class<T> classType) throws ServiceException {
 parsing "/Users/usteiri/Pearson/GLP/code/glp-course-management/src/main/java/com/pearson/glp/cma/model/common/LearningExperienceBase.java": File 'LearningExperienceBase.java', Line 94, Column 15: IDENTIFIER expected instead of '@'
   private Map<@NotBlank String, @NotBlank String> extensions;
 
That's 7 errors, out of 2120 production-level java source files.  This is perhaps the only context in which one of your users can say "Not bad, let's use it!": in our case (performing static analysis to identify bad programming practices), a 0.3% error rate is entirely acceptable. 
 
I therefore intend to use Janino going forward (and skipping doing something a lot more costly with Antlr). 
 
I'd of course be delighted to see the error rate drop to zero, or more realistically (in languages, only a fool would claim perfection), that the few semantic holes exhibited in the above report are flattened.
 
Thanks for your effort, and congrats to both of our teams!
 
Cheers,
 
-rjs
--------- Original Message --------- Subject: Re: [janino-compiler/janino] Parse Type inference syntax (#78)

**Comment by richard-steiger** [comment]
Hi Arno,
 
Between the earlier version and the latest, I discovered that APIs morphed a fair amount.  One impact in particular was what appears to be removal of modifier predicates on fields, specifically isStatic() and isFinal().  In attempting to find the most "natural" alternate API, I found Java.hasAccessModifier, but immediately found it's private.  I'd like to request either restoring the earlier accessors, or make the above method public.
 
Thanks,
 
-rjs
 
--------- Original Message --------- Subject: RE: Re: [janino-compiler/janino] Parse Type inference syntax (#78)
From: rsteiger@ensemblesoft.net
Date: 3/6/19 9:32 pm
To: "janino-compiler/janino" <reply@reply.github.com>, "janino-compiler/janino" <janino@noreply.github.com>
Cc: "Mention" <mention@noreply.github.com>, thomas.fontaine@pearson.com

 Hi Arno,
 
I retested Janino in the same project we've discussed.  The following is a report of errors raised by the Parser (each error occupies 2 lines): 
 
parsing "/Users/usteiri/Pearson/GLP/code/glp-roster-management/src/main/java/com/pearson/glp/roster/data/model/LearningAsset.java": File 'LearningAsset.java', Line 86, Column 15: IDENTIFIER expected instead of '@'
   private Map<@NotBlank String, @NotBlank String> extensions;
 parsing "/Users/usteiri/Pearson/GLP/code/glp-roster-management/src/main/java/com/pearson/glp/roster/data/model/Extends.java": File 'Extends.java', Line 42, Column 16: IDENTIFIER expected instead of '@'
   private List<@NotNull AssetRelationship> sources = new ArrayList<>();
 parsing "/Users/usteiri/Pearson/GLP/code/glp-learning-product-builder/src/main/java/com/pearson/glp/lpb/utils/CommonUtils.java": File 'CommonUtils.java', Line 84, Column 17: Default interface methods not implemented
   default <T> T convertJsonToObject(String jsonFile, Class<T> classType) throws ServiceException {
 parsing "/Users/usteiri/Pearson/GLP/code/glp-learning-experience-composition-kernel/src/main/java/com/pearson/glp/composer/service/impl/LearningExperienceServiceImpl.java": File 'LearningExperienceServiceImpl.java', Line 548, Column 35: ')' expected instead of '::'
         .map(this.productConverter::convert)
 parsing "/Users/usteiri/Pearson/GLP/code/glp-assignment-management/src/main/java/com/pearson/glp/assignment/model/LearningExperience.java": File 'LearningExperience.java', Line 76, Column 16: IDENTIFIER expected instead of '@'
   private List<@NotNull AssetGraphItem> assetGraph;
 parsing "/Users/usteiri/Pearson/GLP/code/glp-productization-service/src/main/java/com/pearson/glp/pdz/utils/CommonUtils.java": File 'CommonUtils.java', Line 58, Column 17: Default interface methods not implemented
   default <T> T convertJsonToObject(String jsonFile, Class<T> classType) throws ServiceException {
 parsing "/Users/usteiri/Pearson/GLP/code/glp-course-management/src/main/java/com/pearson/glp/cma/model/common/LearningExperienceBase.java": File 'LearningExperienceBase.java', Line 94, Column 15: IDENTIFIER expected instead of '@'
   private Map<@NotBlank String, @NotBlank String> extensions;
 
That's 7 errors, out of 2120 production-level java source files.  This is perhaps the only context in which one of your users can say "Not bad, let's use it!": in our case (performing static analysis to identify bad programming practices), a 0.3% error rate is entirely acceptable. 
 
I therefore intend to use Janino going forward (and skipping doing something a lot more costly with Antlr). 
 
I'd of course be delighted to see the error rate drop to zero, or more realistically (in languages, only a fool would claim perfection), that the few semantic holes exhibited in the above report are flattened.
 
Thanks for your effort, and congrats to both of our teams!
 
Cheers,
 
-rjs
--------- Original Message --------- Subject: Re: [janino-compiler/janino] Parse Type inference syntax (#78)

**Comment by aunkrig** [comment]
The syntax element that makes Janino choke is "type annotations", i.e. annotations on *types* (a Java 8 feature), as opposes to the good old annotations on *declarations*. To my knowledge the only Java construct that the Janino parse does not handle to date.

I will open a respective feature request.

**Comment by aunkrig** [comment]
Please subscribe to issue #83 .

**Comment by aunkrig** [comment]
Hey Richard,

you are right, the MODIFIERS API indeed changed significantly.

The reason being is that in old Java versions, modifiers mapped one-to-one to the 16 bit JVM „accessFlag“. As the language evolved and new modifiers were introduced, some of the bits were „overloaded“. Then with Java 5 came annotations, which are (logically) also „modifiers“, although they are not encoded in the access flags. Java 8 and 9 added more access modifiers (e.g. „default“).

So eventually I reimplemented the representation of modifiers completely, from „short accessFlags“ + „boolean defaulT“ + „Annotation[]“ to „Modifier[]“.

Both „Java“ and „UnitCompiler“ have a set of (private) helper methods, as you have noticed, and it would definitely make sense to consolidate them in one public API.

I will do that as soon as possible. Stay tuned.

**Comment by aunkrig** [comment]
All the relevant AST classes now have a set of "is...()" methods to query individual access modifiers, and "getAccess()" and "getAnnotations()" methods.
Please test if that API works for you.
