### ISSUE TITLE
check for compat with java 9 (jdk and/or runtime)

### ISSUE THREAD

**Issue by oontvoo** [janino-compiler/janino#8]
Should do a quick check to make sure janino will run on java 9

**Comment by aunkrig** [comment]
I tested with jdk-9-ea-149.

* ECLIPSE has serious problems with that JRE; it is impossible to configure it in ECLIPSE.
* The janino-tests and the commons-compiler-tests with JANINO run without serious problems.
* The commons-compiler-tests with the JDK implementation don't work at all; one of the reasons being that the `JavaFileManager` interface has changed incompatibly. After modifying JANINO accordingly, other problems occur:
`module jdk.localedata reads package org.codehaus.commons.compiler.tests.bug172 from both java.base and jdk.dynalink (compiler.err.package.clash.from.requires)`

Let's hope ORACLE adds a compatibility to the final JDK!

**Comment by oontvoo** [comment]
Hi Arno,

From your first point, I take it that it's an Eclipse issue, not a janino+java issue? In other words, if I take eclipse out of the picture (and replace it with some other IDE, such as IntelliJ, et al), things would still work?

**Comment by aunkrig** [comment]
Hey Vy,

that's correct. The only problems I found affect the JDK implementation of JANINO, i.e. if you use the `org.codehaus.commons.compiler.jdk.ExpressionEvaluator` instead of the `org.codehaus.janino.ExpressionEvaluator` - which nobody actually does, as far as I know. Also I presume that ORACLE will provide a compatibility layer that hide the changes in the COMPILER API, so eventually also the JDK implementation of JANINO will function with Java 9.
