### ISSUE TITLE
Compiling module-info.java for Java 11 module system

### ISSUE THREAD

**Issue by bernhardttom** [janino-compiler/janino#82]
I'd like to use the Java 11 module system and compile a module-info.java like below.
Is it supported?

The exception is:
```
org.codehaus.commons.compiler.CompileException: Line 1, Column 1: One of 'class enum interface @' expected instead of 'module'
	at org.codehaus.janino.TokenStreamImpl.compileException(TokenStreamImpl.java:362)
	at org.codehaus.janino.TokenStreamImpl.read(TokenStreamImpl.java:182)
	at org.codehaus.janino.Parser.read(Parser.java:3546)
	at org.codehaus.janino.Parser.parsePackageMemberTypeDeclarationRest(Parser.java:374)
	at org.codehaus.janino.Parser.parseCompilationUnit(Parser.java:248)
	at ...
```

module-info.java is:
```
module moduleone {
  exports mycompany.moduleone;\n" +
}
```

**Comment by aunkrig** [comment]
Hey Bernhard,

I just added „modular compilation units“ to the `Parser`, `Unparser` and `Copier`, so you won't get the syntax error any more. So, if you'd use Janino solely for AST Manipulation then you now have full support.

The bad news, however, is that you still get an NYI error when it comes to *compiling*, which is obviously what you want to do. The reason being is that JANINO to date only generates Java *6* class files, which is not a problem because JVMs will *always* be able to run older class files; on the other hand JANINO can not implement newer language features that are based on new JVM features, namely default methods, modules and others.

Unfortunately, it is not easy to generate Java 7+ class files, because these *must* contain the unfortunate `StackMapTable` attribute for each method, and that attribute is so hard to generate... If you want to volunteer, feel free!


CU Arno

**Comment by bernhardttom** [comment]
ok thanks for the update.
